name: Java CI with Maven

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: false
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
        
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml
        
      - name: Run tests
        run: mvn -B test
        
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: java-artifacts
          path: |
            */target/*.jar
            !*/target/*-exec.jar
            !*/target/*.original
          if-no-files-found: warn
          retention-days: 5
