name: Pull Request Validation

on:
  pull_request:
    branches: [ main, master, develop ]
    types: [opened, synchronize, reopened]

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      
      - name: Validate PR
        run: |
          echo "Pull request #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}"
          echo "From branch ${{ github.head_ref }} to ${{ github.base_ref }}"
          echo "Validating PR..."
      
      - name: Build with Maven
        run: mvn -B clean compile
      
      - name: Run tests
        run: mvn -B test
      
      - name: Check test coverage
        run: |
          mvn -B jacoco:report
          # Example threshold checking - can be customized
          echo "Test coverage report generated"
      
      - name: Static code analysis
        run: |
          mvn -B spotbugs:check pmd:check
      
      - name: Dependency check
        run: |
          mvn -B dependency:analyze dependency:tree
          echo "Dependency analysis complete"

  integration-test:
    runs-on: ubuntu-latest
    needs: validate-pr
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      
      - name: Build services
        run: mvn -B clean package -DskipTests
      
      - name: Integration tests
        run: mvn -B verify -Pintegration-test

  report-results:
    runs-on: ubuntu-latest
    needs: [validate-pr, integration-test]
    if: ${{ always() }}
    steps:
      - name: Report results
        run: |
          if [ "${{ needs.validate-pr.result }}" == "success" ] && [ "${{ needs.integration-test.result }}" == "success" ]; then
            echo "All checks passed successfully!"
            exit 0
          else
            echo "Some checks failed. Please check the job logs for details."
            exit 1
          fi
